export const UserActionTypes = {
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  LOG_OUT_USER: "LOG_OUT_USER",
  LOG_OUT_USER_SUCCESS: "LOG_OUT_USER_SUCCESS",
};
